name: Build and Run Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t freight_calculator .

      - name: Run cheapest
        run: docker run -e INPUT="$(cat cheapest.txt)" freight_calculator

      - name: Run cheapest-direct
        run: docker run -e INPUT="$(cat cheapest_direct.txt)" freight_calculator

      - name: Run fastest
        run: docker run -e INPUT="$(cat fastest.txt)" freight_calculator

      - name: Run fastest-direct
        run: docker run -e INPUT="$(cat fastest_direct.txt)" freight_calculator
